name: deploy

on:
  push:
    branches:
      - main
jobs:
  AUTO_DEPLOY:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: git 다운로드
        run: |
            sudo apt update
            sudo apt install git

      - name: node 다운로드
        run: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
            nvm install node

      - name: pm 다운로드
        run: |
            npm install -g pm2
       
      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          password: ${{ secrets.PASSWORD }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          script: |
            cd Waa-backend
            ls
            pm2 kill
            git pull main
            npm run build
            npm run start
