name: deploy

on:
  push:
    branches:
      - main

jobs:
  AUTO_DEPLOY:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          password: ${{ secrets.PASSWORD }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          env: ${{ secrets.ENV }}
          script: |
            touch .env
            echo $env | base64 --decode >> .env
            export DATABASE_URL=${{ secrets.DATABASE_URL }}
            sudo apt update
            sudo apt install git
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            nvm install node
            npm install -g pm2
            cd Waa-backend
            ls
            pm2 kill
            git pull origin main
            npm run build
            npm run start:prod
